In [59]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [60]:
# df = pd.read_json(r'../data/reviews_Electronics_5.json.gz', lines = True)

In [61]:
# df

In [62]:
'''import gzip
import json

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    first_line = json.loads(next(f))

print(first_line)'''

"import gzip\nimport json\n\nwith gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:\n    first_line = json.loads(next(f))\n\nprint(first_line)"

In [63]:
# print(first_line.keys())

In [64]:
'''data = []

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    for line in f:
        obj = json.loads(line)

        data.append({
            "asin": obj.get("parent_asin"),
            "title": obj.get("title"),
            "brand": obj.get("store"),
            "category": obj.get("categories"),
            "description": obj.get("description"),
            "avg_rating": obj.get("average_rating"),
            "rating_count": obj.get("rating_number"),
            "bought_together": obj.get("bought_together")
        })

df_meta = pd.DataFrame(data)'''

'data = []\n\nwith gzip.open(\'../data/meta_Electronics.jsonl.gz\', \'rt\', encoding=\'utf-8\') as f:\n    for line in f:\n        obj = json.loads(line)\n\n        data.append({\n            "asin": obj.get("parent_asin"),\n            "title": obj.get("title"),\n            "brand": obj.get("store"),\n            "category": obj.get("categories"),\n            "description": obj.get("description"),\n            "avg_rating": obj.get("average_rating"),\n            "rating_count": obj.get("rating_number"),\n            "bought_together": obj.get("bought_together")\n        })\n\ndf_meta = pd.DataFrame(data)'

In [65]:
# df_meta

In [66]:
# df

In [67]:
# df_final = df.merge(df_meta, on="asin", how="inner")

In [68]:
# df_final.head()

In [69]:
# df_final.shape

In [70]:
# df_final['bought_together'].unique()

In [71]:
# df_final.to_csv('Final_Merged_Raw_Dataset.csv', index = False)

In [72]:
df1 = pd.read_csv(r'../data/Final_Merged_Raw_Dataset.csv')

In [73]:
df1.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,title,brand,category,description,avg_rating,rating_count,bought_together
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN

### EDA

In [74]:
df1.shape

(903720, 16)

In [75]:
df1.isna().sum()

reviewerID              0
asin                    0
reviewerName        12061
helpful                 0
reviewText            548
overall                 0
summary                 9
unixReviewTime          0
reviewTime              0
title                  14
brand                1938
category                0
description             0
avg_rating              0
rating_count            0
bought_together    903720
dtype: int64

In [76]:
df1.duplicated().sum()

np.int64(0)

In [77]:
df1.drop(columns = ['bought_together'], inplace = True)

In [78]:
df1.shape

(903720, 15)

In [79]:
df1.drop(columns = ['reviewerName'], inplace = True)

In [80]:
df1 = df1.drop(columns=[
    'reviewerID',
    'asin',
    'helpful',
    'overall',
    'summary',
    'unixReviewTime',
    'reviewTime',
    'avg_rating',
    'rating_count'
])

In [81]:
df1.head()

,reviewText,title,brand,category,description
0,We got this GPS for my husband who is an (OTR)...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
1,"I'm a professional OTR truck driver, and I bou...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
2,"Well, what can I say. I've had this unit in m...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
3,"Not going to write a long review, even thought...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
4,I've had mine for a year and here's what we go...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."

In [82]:
df1.shape

(903720, 5)

In [83]:
df1.isna().sum()

reviewText      548
title            14
brand          1938
category          0
description       0
dtype: int64

In [84]:
df1['reviewText'] = df1['reviewText'].fillna('')

In [85]:
df1 = df1.dropna(subset = ['title'])

In [86]:
df1['brand'].unique()

array(['Rand McNally', 'Barnes & Noble', 'VideoSecu', ..., 'AUSDOM',
       'TaoTronics', 'Ritz Gear'], dtype=object)

In [87]:
df1.isna().sum()

reviewText        0
title             0
brand          1938
category          0
description       0
dtype: int64

In [88]:
df1['brand'] = df1['brand'].fillna('')

In [89]:
df1.isna().sum()

reviewText     0
title          0
brand          0
category       0
description    0
dtype: int64

In [90]:
df1.head()

,reviewText,title,brand,category,description
0,We got this GPS for my husband who is an (OTR)...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
1,"I'm a professional OTR truck driver, and I bou...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
2,"Well, what can I say. I've had this unit in m...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
3,"Not going to write a long review, even thought...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
4,I've had mine for a year and here's what we go...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."

In [91]:
df1 = df1.groupby('title').agg({
    'description': 'first',
    'category': 'first',
    'brand': 'first',
    'reviewText': ' '.join
}).reset_index()

In [92]:
df1.shape

(39936, 5)

In [93]:
df1

,title,description,category,brand,reviewText
0,"""C"" Size Battery Shell Adapter for AA Batterie...",['Using the PROAA2C c-size adapter you can pow...,"['Electronics', 'Power Accessories', 'AC Adapt...",Lenmar,Does what it says on the tin. Fits neatly and ...
1,"""D"" Size Battery Shell Adapter for AA Batterie...",['Using the PROAA2D d-size adapter you can pow...,"['Electronics', 'Power Accessories', 'AC Adapt...",Lenmar,I have these in a baby swing since buying a 4 ...
2,(1 Pair) Universal satellite surround sound sp...,['Speaker Wall Mounting Bracket - Black or Sil...,"['Electronics', 'Accessories & Supplies', 'Mou...",EZ Mounts,"I have a Bose Cinemate system (original), whic..."
3,"(10 Packs) Fotasy Stainless Steel 3/8"" to 1/4""...","['These 1/4"" to 3/8"" Screw Adapter Converter R...","['Electronics', 'Camera & Photo']",Fotasy,I bought these to install DMKPhoto Heavy Duty ...
4,(10 Pcs Bundle) 5 Center Pinch Lens Cap (55mm)...,[],"['Electronics', 'Camera & Photo', 'Accessories...",WAAO,Every photographer needs spare lens caps. This...
...,...,...,...,...,...
39931,welspo Wireless USB Handheld Finger Trackball ...,[],"['Electronics', 'Computers & Accessories', 'Co...",welspo,I had been using the wired version of this mou...
39932,xPrintServer Network Edition,"[""xPrintServer is an easy-to-use, affordable '...","['Electronics', 'Computers & Accessories', 'La...",Lantronix,"Although I am very computer savvy, I didn't qu..."
39933,zBoost YX039-PCS-CEL Dual Band Directional Out...,['The YX039-PCS-CEL dual-band outdoor signal a...,"['Electronics', 'Television & Video', 'Accesso...",zBoost,was told to order this to help amp. did not ma...
39934,~Upek Eikon Trueme - Fingerprint reader - USB ...,"[""With this UPEK Eikon TrueMe USB Fingerprint ...","['Electronics', 'Security & Surveillance', 'Bi...",Eikon,This device does not work with Windows 7. It d...
39935,“Discontinued by Manufacturer” D-Link Smart Pl...,['The mydlink Wi-Fi Smart Plug (DSP-W215) is a...,"['Electronics', 'Computers & Accessories', 'Ne...",D-Link,---Update 5-23-2014----------The plugs were ab...

In [94]:
# Extracting the text from description column

import ast

def clean_description(text):
    try:
        lst = ast.literal_eval(text)  # convert string → list
        if isinstance(lst, list):
            return ' '.join(lst)  # join list elements
        return text
    except:
        return ''

df1['description'] = df1['description'].apply(clean_description)

In [95]:
# Extracting the text from category column
import ast

def clean_category(text):
    try:
        lst = ast.literal_eval(text)
        if isinstance(lst, list):
            return ' '.join(lst)
        return text
    except:
        return ''

df1['category'] = df1['category'].apply(clean_category)

In [96]:
df1.head()

,title,description,category,brand,reviewText
0,"""C"" Size Battery Shell Adapter for AA Batterie...",Using the PROAA2C c-size adapter you can power...,Electronics Power Accessories AC Adapters,Lenmar,Does what it says on the tin. Fits neatly and ...
1,"""D"" Size Battery Shell Adapter for AA Batterie...",Using the PROAA2D d-size adapter you can power...,Electronics Power Accessories AC Adapters,Lenmar,I have these in a baby swing since buying a 4 ...
2,(1 Pair) Universal satellite surround sound sp...,Speaker Wall Mounting Bracket - Black or Silve...,Electronics Accessories & Supplies Mounts Spea...,EZ Mounts,"I have a Bose Cinemate system (original), whic..."
3,"(10 Packs) Fotasy Stainless Steel 3/8"" to 1/4""...","These 1/4"" to 3/8"" Screw Adapter Converter Red...",Electronics Camera & Photo,Fotasy,I bought these to install DMKPhoto Heavy Duty ...
4,(10 Pcs Bundle) 5 Center Pinch Lens Cap (55mm)...,,Electronics Camera & Photo Accessories Lens Ac...,WAAO,Every photographer needs spare lens caps. This...

In [97]:
df1['combined_text'] = (
    df1['title'] * 3 + " " +
    df1['description'] * 2 + " " +
    df1['category'] * 2 + " " +
    df1['brand']
)

In [98]:
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)  # remove special chars
    return text
df1['combined_text'] = df1['combined_text'].apply(clean_text)

In [99]:
df1.head()

,title,description,category,brand,reviewText,combined_text
0,"""C"" Size Battery Shell Adapter for AA Batterie...",Using the PROAA2C c-size adapter you can power...,Electronics Power Accessories AC Adapters,Lenmar,Does what it says on the tin. Fits neatly and ...,c size battery shell adapter for aa batteries ...
1,"""D"" Size Battery Shell Adapter for AA Batterie...",Using the PROAA2D d-size adapter you can power...,Electronics Power Accessories AC Adapters,Lenmar,I have these in a baby swing since buying a 4 ...,d size battery shell adapter for aa batteries ...
2,(1 Pair) Universal satellite surround sound sp...,Speaker Wall Mounting Bracket - Black or Silve...,Electronics Accessories & Supplies Mounts Spea...,EZ Mounts,"I have a Bose Cinemate system (original), whic...",1 pair universal satellite surround sound spea...
3,"(10 Packs) Fotasy Stainless Steel 3/8"" to 1/4""...","These 1/4"" to 3/8"" Screw Adapter Converter Red...",Electronics Camera & Photo,Fotasy,I bought these to install DMKPhoto Heavy Duty ...,10 packs fotasy stainless steel 38 to 14 reduc...
4,(10 Pcs Bundle) 5 Center Pinch Lens Cap (55mm)...,,Electronics Camera & Photo Accessories Lens Ac...,WAAO,Every photographer needs spare lens caps. This...,10 pcs bundle 5 center pinch lens cap 55mm and...

In [100]:
from sentence_transformers import SentenceTransformer

# Load the pre-trained model
print("Loading the embedding model...")
model = SentenceTransformer('all-MiniLM-L6-v2')
print("Model loaded successfully!")

Loading the embedding model...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Model loaded successfully!

In [101]:
product_texts = df1['combined_text'].tolist()

In [102]:
import os
import numpy as np

if os.path.exists("../models/product_embeddings.npy"):
    print("✅ Loading saved embeddings...")
    product_embeddings = np.load("../models/product_embeddings.npy")
else:
    print("⏳ Generating embeddings (first time only)...")
    product_embeddings = model.encode(
        product_texts,
        batch_size=64,
        show_progress_bar=True
    )
    np.save("../models/product_embeddings.npy", product_embeddings)
    print("✅ Embeddings saved!")

⏳ Generating embeddings (first time only)...

Batches:   0%|          | 0/624 [00:00<?, ?it/s]

✅ Embeddings saved!

In [103]:
#Building the Model
from sklearn.neighbors import NearestNeighbors

nn_model = NearestNeighbors(
    n_neighbors=6,      # 5 recommendations + 1 itself
    metric='cosine'
)

nn_model.fit(product_embeddings)

NearestNeighbors(metric='cosine', n_neighbors=6)

In [104]:
def recommend_products(query, top_k=5):
    # Convert query → embedding
    query_embedding = model.encode([query])
    
    # Find nearest neighbors
    distances, indices = nn_model.kneighbors(query_embedding, n_neighbors=top_k)
    
    results = df1.iloc[indices[0]]
    
    return results[['title', 'brand', 'category']]

In [106]:
recommend_products("bluetooth speaker")

,title,brand,category
5976,Bose® SoundLink® Bluetooth Mobile Speaker II –...,Bose,Electronics Portable Audio & Video Portable Sp...
15154,Hercules4769217 Wireless Bluetooth Speaker (Bl...,Hercules DJ,Electronics Portable Audio & Video Portable Sp...
15142,Hercules Portable Bluetooth Speaker (Black),HERCULES,Electronics Portable Audio & Video Portable Sp...
15145,Hercules Wireless Bluetooth Speaker (White/Green),HERCULES,Electronics Portable Audio & Video Portable Sp...
33637,Spracht Aura BluNote Portable Wireless Speaker...,Spracht,Electronics Portable Audio & Video Portable Sp...

In [107]:
recommend_products("portable bluetooth speaker")

,title,brand,category
15142,Hercules Portable Bluetooth Speaker (Black),HERCULES,Electronics Portable Audio & Video Portable Sp...
9832,DIVOOM Bluetune Solo Blue FREE CARRYING POUCH ...,Divoom,Electronics Portable Audio & Video Portable Sp...
2562,Acoustic Research ARS60RD Bluetooth Wireless S...,Acoustic Research,Electronics Portable Audio & Video Portable Sp...
33637,Spracht Aura BluNote Portable Wireless Speaker...,Spracht,Electronics Portable Audio & Video Portable Sp...
5150,Belkin Fusive Portable Bluetooth Speaker (Disc...,Belkin,Electronics Portable Audio & Video Portable Sp...

In [108]:
recommend_products("sony bluetooth speaker")

,title,brand,category
33213,Sony SRSBT100 Bluetooth Stereo Speakers (Disco...,Sony,Electronics Portable Audio & Video Portable Sp...
33206,Sony SRS-BTM30 Bluetooth Wireless Speaker,Sony,Electronics Portable Audio & Video Portable Sp...
29189,Sabrent Bluetooth Wireless Adapter for Home St...,SABRENT,Electronics Computers & Accessories Networking...
5976,Bose® SoundLink® Bluetooth Mobile Speaker II –...,Bose,Electronics Portable Audio & Video Portable Sp...
33209,Sony SRS-RF90RK Wireless Speaker System with B...,Sony,Electronics Portable Audio & Video Portable Sp...

In [111]:
recommend_products("earphones")

,title,brand,category
32866,Sony MDR-J20 h.ear Stereo Headphones (White),Sony,"Electronics Headphones, Earbuds & Accessories ..."
33467,Sound2 in-ear headphone earbuds - Black,Sound-Squared,"Electronics Headphones, Earbuds & Accessories ..."
32911,Sony MDRG72LP Behind-the-neck Compact Foldin,Sony,"Electronics Headphones, Earbuds & Accessories ..."
4143,Audio Technica ATH-A900 Audiophile Closed-Back...,Audio-Technica,"Electronics Headphones, Earbuds & Accessories ..."
19545,Lobers Women's Solid Headphone Earmuffs,Lobers,"Electronics Headphones, Earbuds & Accessories ..."