In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
# df = pd.read_json(r'../data/reviews_Electronics_5.json.gz', lines = True)

In [3]:
# df

In [4]:
'''import gzip
import json

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    first_line = json.loads(next(f))

print(first_line)'''

"import gzip\nimport json\n\nwith gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:\n    first_line = json.loads(next(f))\n\nprint(first_line)"

In [5]:
# print(first_line.keys())

In [6]:
'''data = []

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    for line in f:
        obj = json.loads(line)

        data.append({
            "asin": obj.get("parent_asin"),
            "title": obj.get("title"),
            "brand": obj.get("store"),
            "category": obj.get("categories"),
            "description": obj.get("description"),
            "avg_rating": obj.get("average_rating"),
            "rating_count": obj.get("rating_number"),
            "bought_together": obj.get("bought_together")
        })

df_meta = pd.DataFrame(data)'''

'data = []\n\nwith gzip.open(\'../data/meta_Electronics.jsonl.gz\', \'rt\', encoding=\'utf-8\') as f:\n    for line in f:\n        obj = json.loads(line)\n\n        data.append({\n            "asin": obj.get("parent_asin"),\n            "title": obj.get("title"),\n            "brand": obj.get("store"),\n            "category": obj.get("categories"),\n            "description": obj.get("description"),\n            "avg_rating": obj.get("average_rating"),\n            "rating_count": obj.get("rating_number"),\n            "bought_together": obj.get("bought_together")\n        })\n\ndf_meta = pd.DataFrame(data)'

In [7]:
# df_meta

In [8]:
# df

In [9]:
# df_final = df.merge(df_meta, on="asin", how="inner")

In [10]:
# df_final.head()

In [11]:
# df_final.shape

In [12]:
# df_final['bought_together'].unique()

In [13]:
# df_final.to_csv('Final_Merged_Raw_Dataset.csv', index = False)

In [32]:
df1 = pd.read_csv(r'../data/Final_Merged_Raw_Dataset.csv')

In [33]:
df1.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,title,brand,category,description,avg_rating,rating_count,bought_together
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN

### EDA

In [34]:
df1.shape

(903720, 16)

In [35]:
df1.isna().sum()

reviewerID              0
asin                    0
reviewerName        12061
helpful                 0
reviewText            548
overall                 0
summary                 9
unixReviewTime          0
reviewTime              0
title                  14
brand                1938
category                0
description             0
avg_rating              0
rating_count            0
bought_together    903720
dtype: int64

In [36]:
df1.duplicated().sum()

np.int64(0)

In [37]:
df1.drop(columns = ['bought_together'], inplace = True)

In [38]:
df1.shape

(903720, 15)

In [39]:
df1.drop(columns = ['reviewerName'], inplace = True)

In [40]:
df1 = df1.drop(columns=[
    'reviewerID',
    'asin',
    'helpful',
    'overall',
    'summary',
    'unixReviewTime',
    'reviewTime',
    'avg_rating',
    'rating_count'
])

In [41]:
df1.head()

,reviewText,title,brand,category,description
0,We got this GPS for my husband who is an (OTR)...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
1,"I'm a professional OTR truck driver, and I bou...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
2,"Well, what can I say. I've had this unit in m...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
3,"Not going to write a long review, even thought...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
4,I've had mine for a year and here's what we go...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."

In [42]:
df1.shape

(903720, 5)

In [43]:
df1.isna().sum()

reviewText      548
title            14
brand          1938
category          0
description       0
dtype: int64

In [44]:
df1['reviewText'] = df1['reviewText'].fillna('')

In [45]:
df1 = df1.dropna(subset = ['title'])

In [46]:
df1['brand'].unique()

array(['Rand McNally', 'Barnes & Noble', 'VideoSecu', ..., 'AUSDOM',
       'TaoTronics', 'Ritz Gear'], shape=(4800,), dtype=object)

In [47]:
df1.isna().sum()

reviewText        0
title             0
brand          1938
category          0
description       0
dtype: int64

In [48]:
df1['brand'] = df1['brand'].fillna('')

In [49]:
df1.isna().sum()

reviewText     0
title          0
brand          0
category       0
description    0
dtype: int64

In [50]:
df1.head()

,reviewText,title,brand,category,description
0,We got this GPS for my husband who is an (OTR)...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
1,"I'm a professional OTR truck driver, and I bou...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
2,"Well, what can I say. I've had this unit in m...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
3,"Not going to write a long review, even thought...",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."
4,I've had mine for a year and here's what we go...,Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D..."