In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# df = pd.read_json(r'../data/reviews_Electronics_5.json.gz', lines = True)

In [ ]:
# df

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013"
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010"
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010"
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010"
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011"
...,...,...,...,...,...,...,...,...,...
1689183,A34BZM6S9L7QI4,B00LGQ6HL8,"Candy Cane ""Is it just me?""","[1, 1]",Burned these in before listening to them for a...,5,Boom -- Pop -- Pow. These deliver.,1405555200,"07 17, 2014"
1689184,A1G650TTTHEAL5,B00LGQ6HL8,"Charles Spanky ""Zumina Reviews""","[0, 0]",Some people like DJ style headphones or earbud...,5,"Thin and light, without compromising on sound ...",1405382400,"07 15, 2014"
1689185,A25C2M3QF9G7OQ,B00LGQ6HL8,Comdet,"[0, 0]",I&#8217;m a big fan of the Brainwavz S1 (actua...,5,Same form factor and durability as the S1 with...,1405555200,"07 17, 2014"
1689186,A1E1LEVQ9VQNK,B00LGQ6HL8,J. Chambers,"[0, 0]","I've used theBrainwavz S1 In Ear Headphones, a...",5,Superb audio quality in a very comfortable set...,1405641600,"07 18, 2014"
1689187,A2NYK9KWFMJV4Y,B00LGQ6HL8,"Mike Tarrani ""Jazz Drummer""","[0, 0]",Normally when I receive a review sample I can ...,5,Exceptional sound,1405209600,"07 13, 2014"

In [ ]:
'''import gzip
import json

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    first_line = json.loads(next(f))

print(first_line)'''

{'main_category': 'All Electronics', 'title': 'FS-1051 FATSHARK TELEPORTER V3 HEADSET', 'average_rating': 3.5, 'rating_number': 6, 'features': [], 'description': ['Teleporter V3 The “Teleporter V3” kit sets a new level of value in the FPV world with Fat Shark renowned performance and quality. The fun of FPV is experienced firsthand through the large screen FPV headset with integrated NexwaveRF receiver technology while simultaneously recording onboard HD footage with the included “PilotHD” camera. The “Teleporter V3” kit comes complete with everything you need to step into the cockpit of your FPV vehicle. We’ve included our powerful 250mW 5.8Ghz transmitter, 25 degree FOV headset (largest QVGA display available), the brand new “PilotHD” camera with live AV out and all the cables, antennas and connectors needed.'], 'price': None, 'images': [{'thumb': 'https://m.media-amazon.com/images/I/41qrX56lsYL._AC_US40_.jpg', 'large': 'https://m.media-amazon.com/images/I/41qrX56lsYL._AC_.jpg', 'variant': 'MAIN', 'hi_res': None}], 'videos': [], 'store': 'Fat Shark', 'categories': ['Electronics', 'Television & Video', 'Video Glasses'], 'details': {'Date First Available': 'August 2, 2014', 'Manufacturer': 'Fatshark'}, 'parent_asin': 'B00MCW7G9M', 'bought_together': None}

In [ ]:
# print(first_line.keys())

dict_keys(['main_category', 'title', 'average_rating', 'rating_number', 'features', 'description', 'price', 'images', 'videos', 'store', 'categories', 'details', 'parent_asin', 'bought_together'])

In [ ]:
'''data = []

with gzip.open('../data/meta_Electronics.jsonl.gz', 'rt', encoding='utf-8') as f:
    for line in f:
        obj = json.loads(line)

        data.append({
            "asin": obj.get("parent_asin"),
            "title": obj.get("title"),
            "brand": obj.get("store"),
            "category": obj.get("categories"),
            "description": obj.get("description"),
            "avg_rating": obj.get("average_rating"),
            "rating_count": obj.get("rating_number"),
            "bought_together": obj.get("bought_together")
        })

df_meta = pd.DataFrame(data)'''

In [ ]:
# df_meta

,asin,title,brand,category,description,avg_rating,rating_count,bought_together
0,B00MCW7G9M,FS-1051 FATSHARK TELEPORTER V3 HEADSET,Fat Shark,"[Electronics, Television & Video, Video Glasses]",[Teleporter V3 The “Teleporter V3” kit sets a ...,3.5,6,None
1,B00YT6XQSE,Ce-H22B12-S1 4Kx2K Hdmi 4Port,SIIG,"[Electronics, Television & Video, Accessories,...",[HDMI In - HDMI Out],5.0,1,None
2,B07SM135LS,Digi-Tatoo Decal Skin Compatible With MacBook ...,Digi-Tatoo,"[Electronics, Computers & Accessories, Laptop ...",[],4.5,246,None
3,B089CNGZCW,NotoCity Compatible with Vivoactive 4 band 22m...,NotoCity,"[Electronics, Wearable Technology, Clips, Arm ...",[],4.5,233,None
4,B004E2Z88O,Motorola Droid X Essentials Combo Pack,Verizon,"[Electronics, Computers & Accessories, Compute...",[all Genuine High Quality Motorola Made Access...,3.8,64,None
...,...,...,...,...,...,...,...,...
1610007,B003NUIU9M,"Wintec FileMate Pro USB Flash Drive, 3FMUSB32G...",Wintec Industries,"[Electronics, Computers & Accessories, Data St...",[--New in retail packaging --Fast USB 2.0 data...,5.0,1,None
1610008,B0BHVY33TL,Tsugar Noise Reduction Wireless Headphones Blu...,Tsugar,"[Electronics, Headphones, Earbuds & Accessorie...",[Description: 100% brand new high quality 1.Hi...,1.0,2,None
1610009,B09SQGRFFH,"Hardshell Case for MacBook Pro (16-inch, 2021)...",Incase Designs,"[Electronics, Computers & Accessories, Laptop ...",[],4.6,11,None
1610010,B091JWCSG5,"FYY 12-13.3"" Laptop Sleeve Case Bag, PU Leathe...",FYY,"[Electronics, Computers & Accessories, Laptop ...",[],4.0,35,None
1610011,B08K7KC4GR,4MP Full Time Color Night Vision POE IP Camera...,VIVSKY,"[Electronics, Camera & Photo, Video Surveillan...","[Camera, Image Sensor: 1/1.8"" Progressive Scan...",4.1,10,None

In [ ]:
# df

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013"
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010"
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010"
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010"
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011"
...,...,...,...,...,...,...,...,...,...
1689183,A34BZM6S9L7QI4,B00LGQ6HL8,"Candy Cane ""Is it just me?""","[1, 1]",Burned these in before listening to them for a...,5,Boom -- Pop -- Pow. These deliver.,1405555200,"07 17, 2014"
1689184,A1G650TTTHEAL5,B00LGQ6HL8,"Charles Spanky ""Zumina Reviews""","[0, 0]",Some people like DJ style headphones or earbud...,5,"Thin and light, without compromising on sound ...",1405382400,"07 15, 2014"
1689185,A25C2M3QF9G7OQ,B00LGQ6HL8,Comdet,"[0, 0]",I&#8217;m a big fan of the Brainwavz S1 (actua...,5,Same form factor and durability as the S1 with...,1405555200,"07 17, 2014"
1689186,A1E1LEVQ9VQNK,B00LGQ6HL8,J. Chambers,"[0, 0]","I've used theBrainwavz S1 In Ear Headphones, a...",5,Superb audio quality in a very comfortable set...,1405641600,"07 18, 2014"
1689187,A2NYK9KWFMJV4Y,B00LGQ6HL8,"Mike Tarrani ""Jazz Drummer""","[0, 0]",Normally when I receive a review sample I can ...,5,Exceptional sound,1405209600,"07 13, 2014"

In [ ]:
# df_final = df.merge(df_meta, on="asin", how="inner")

In [ ]:
# df_final.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,title,brand,category,description,avg_rating,rating_count,bought_together
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"[Electronics, GPS, Finders & Accessories, GPS ...","[Product description, **** Shipped by 2-3 DAY ...",3.6,73,None
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"[Electronics, GPS, Finders & Accessories, GPS ...","[Product description, **** Shipped by 2-3 DAY ...",3.6,73,None
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"[Electronics, GPS, Finders & Accessories, GPS ...","[Product description, **** Shipped by 2-3 DAY ...",3.6,73,None
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"[Electronics, GPS, Finders & Accessories, GPS ...","[Product description, **** Shipped by 2-3 DAY ...",3.6,73,None
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"[Electronics, GPS, Finders & Accessories, GPS ...","[Product description, **** Shipped by 2-3 DAY ...",3.6,73,None

In [ ]:
# df_final.shape

(903720, 16)

In [ ]:
# df_final['bought_together'].unique()

array([None], dtype=object)

In [ ]:
# df_final.to_csv('Final_Merged_Raw_Dataset.csv', index = False)

In [3]:
df1 = pd.read_csv(r'../data/Final_Merged_Raw_Dataset.csv')

In [4]:
df1.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,title,brand,category,description,avg_rating,rating_count,bought_together
0,AO94DHGC771SJ,0528881469,amazdnu,"[0, 0]",We got this GPS for my husband who is an (OTR)...,5,Gotta have GPS!,1370131200,"06 2, 2013",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
1,AMO214LNFCEI4,0528881469,Amazon Customer,"[12, 15]","I'm a professional OTR truck driver, and I bou...",1,Very Disappointed,1290643200,"11 25, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
2,A3N7T0DY83Y4IG,0528881469,C. A. Freeman,"[43, 45]","Well, what can I say. I've had this unit in m...",3,1st impression,1283990400,"09 9, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
3,A1H8PY3QHMQQA0,0528881469,"Dave M. Shaw ""mack dave""","[9, 10]","Not going to write a long review, even thought...",2,"Great grafics, POOR GPS",1290556800,"11 24, 2010",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN
4,A24EV6RXELQZ63,0528881469,Wayne Smith,"[0, 0]",I've had mine for a year and here's what we go...,1,"Major issues, only excuses for support",1317254400,"09 29, 2011",Rand McNally 528881469 7-inch Intelliroute TND...,Rand McNally,"['Electronics', 'GPS, Finders & Accessories', ...","['Product description', '**** Shipped by 2-3 D...",3.6,73,NaN